<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN466277" failures="2" tests="3" name="All Functional Tests" time="28.288" errors="0" timestamp="2025-07-31T09:58:20 IST">
  <testcase classname="tests.BaseTest" name="testInvalidMobileListing" time="10.965">
    <failure type="java.lang.AssertionError" message="Invalid mobile listing test failed.">
      <![CDATA[java.lang.AssertionError: Invalid mobile listing test failed.
at tests.BaseTest.testInvalidMobileListing(BaseTest.java:97)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testInvalidMobileListing -->
  <testcase classname="tests.BaseTest" name="testCarWashSearch" time="10.965">
    <failure type="java.lang.AssertionError" message="Car wash search failed due to exception.">
      <![CDATA[java.lang.AssertionError: Car wash search failed due to exception.
at tests.BaseTest.testCarWashSearch(BaseTest.java:68)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testCarWashSearch -->
  <testcase classname="tests.BaseTest" name="testGymSearchAndExcelExport" time="17.741"/>
</testsuite> <!-- All Functional Tests -->
